#include "D2_data.h"

//TYPE NAME & CHOOSE CHARACTER VARIABLES
int D2_PLAYER = 1;
string D2_PLAYER01_NAME = "";
string D2_PLAYER02_NAME = "";
int D2_PLAYER01_CHARACTER = 1;
int D2_PLAYER02_CHARACTER = 1;

//SETTINGS
int D2_BACKGROUND_MUSIC;
int D2_INGAME_MUSIC;
int D2_WHICH_SETTING = 0;